import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
	page: {
		height: '100%',
		width: '100%',
		paddingBottom: 25,
		boxSizing: 'border-box',
	},
	container: {
		flex: 1,
		marginTop: 80,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	infoContainer: {
		alignItems: 'center',
	},
	titleSvg: {
		width: 48,
		height: 48,
		borderRadius: 50,
		backgroundColor: '#F2FAF7',
		borderWidth: 1,
		borderColor: '#E9F7F2',
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
	},
	ava: {
		width: 48,
		height: 48,
		borderRadius: 50,
	},
	authInfo: {
		display: 'flex',
		alignItems: 'center',
		marginTop: 5,
		marginBottom: 30,
		gap: 10,
	},
	email: {
		color: '#06070A',
		fontWeight: '500',
		fontSize: 15,
		lineHeight: 24,
		letterSpacing: 0,
		textAlign: 'center',
	},
	changeAccount: {
		color: '#FA8A34',
		fontWeight: '400',
		fontSize: 15,
		lineHeight: 16,
		letterSpacing: 0,
		textAlign: 'center',
	},
	titleContainer: {
		width: '100%',
		alignItems: 'center',
		gap: 5,
	},
	title: {
		fontSize: 15,
		lineHeight: 24,
		fontWeight: 500,
		marginBottom: 30,
		textAlign: 'center',
	},
	pinCodeContainer: {
		display: 'flex',
		alignItems: 'center',
		gap: 10,
	},
	keyboardContainer: {
		width: '100%',
		display: 'flex',
		alignItems: 'center',
	},
	keyboard: {
		paddingTop: 15,
		paddingBottom: 15,
		boxSizing: 'border-box',
		borderTopWidth: 1,
		borderBottomWidth: 1,
		borderColor: '#D9D9D9',
		width: '100%',
	},
	explainText: {
		fontWeight: 400,
		fontSize: 15,
		color: '#606773',
		lineHeight: 16,
	},
	input: {
		borderWidth: 1,
		borderColor: '#ccc',
		padding: 15,
		borderRadius: 8,
		marginBottom: 20,
		fontSize: 18,
		textAlign: 'center',
	},
	button: {
		width: '100%',
		padding: 15,
		boxSizing: 'border-box',
	},
});
