import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
	page: {
		flex: 1,
		width: '100%',
	},
	container: {
		width: '100%',
		display: 'flex',
	},
	welcomeContainer: {
		width: '100%',
		height: 296,
		borderBottomLeftRadius: 28,
		borderBottomRightRadius: 28,
		opacity: 1,
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
	},
	yourName: {
		fontWeight: '400',
		fontStyle: 'normal',
		fontSize: 13,
		lineHeight: 16,
		letterSpacing: 0,
		textAlign: 'center',
		color: '#fff',
	},
	welcomeText: {
		fontWeight: '700',
		fontStyle: 'normal',
		fontSize: 28,
		lineHeight: 32,
		letterSpacing: 0,
		textAlign: 'center',
		color: '#fff',
	},
	content: {
		paddingHorizontal: 20,
		boxSizing: 'border-box',
		marginTop: 20,
		display: 'flex',
		gap: 30,
	},
	testTask: {
		width: '100%',
		height: 144,
		backgroundColor: '#fff',
		borderRadius: 16,
		display: 'flex',
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		padding: 8,
		boxSizing: 'border-box',
	},
	taskInfo: {
		display: 'flex',
		justifyContent: 'space-between',
		height: '100%',
		padding: 20,
		boxSizing: 'border-box',
		width: 160,
	},
	infoLinks: {
		display: 'flex',
		gap: 10,
	},
	taskTitle: {
		fontWeight: '500',
		fontStyle: 'normal',
		fontSize: 15,
		lineHeight: 15,
		letterSpacing: 0,
		color: '#06070A',
	},
	taskSubTitle: {
		fontWeight: '400',
		fontStyle: 'normal',
		fontSize: 13,
		lineHeight: 13,
		letterSpacing: 0,
		color: '#858C94',
	},
	goCallContainer: {
		display: 'flex',
		flexDirection: 'row',
		width: '100%',
		justifyContent: 'space-between',
	},
	callText: {
		fontWeight: '500',
		fontStyle: 'normal',
		fontSize: 15,
		lineHeight: 24,
		letterSpacing: 0,
		color: '#009E81',
	},
	taskImg: {
		width: 127,
		height: 128,
		backgroundColor: '#2b8aa0',
		borderRadius: 20,
		display: 'flex',
		alignItems: 'center',
		padding: 8,
		boxSizing: 'border-box',
	},
	rectangle: {
		width: 93,
		height: 93,
		borderColor: 'transparent',
		borderBottomColor: 'rgba(255,255,255,0.5)',
		borderRadius: 32,
		borderWidth: 1,
	},
	horizontalMenu: {
		paddingHorizontal: 20,
		marginTop: 10,
	},
	beforeStartItems: {
		display: 'flex',
		gap: 10,
	},
	startItems: {
		display: 'flex',
		flexDirection: 'row',
		gap: 15,
	},
	startItem: {
		width: 233,
		height: 152,
		borderRadius: 16,
		backgroundColor: '#636363',
		padding: 20,
		boxSizing: 'border-box',
		display: 'flex',
		justifyContent: 'space-between',
	},
	startTitle: {
		color: '#fff',
		fontWeight: '500',
		fontStyle: 'normal',
		fontSize: 15,
		lineHeight: 24,
		letterSpacing: 0,
		width: '100%',
		flexShrink: 1,
	},
	beforeStartText: {
		fontWeight: '400',
		fontStyle: 'normal',
		fontSize: 15,
		lineHeight: 16,
		letterSpacing: 0,
		color: '#606773',
	},
	titleContainer: {
		display: 'flex',
		flexDirection: 'row',
		gap: 10,
	},
	logoStart: {
		width: 48,
		height: 48,
		backgroundColor: '#FA8A34',
		borderRadius: 50,
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		boxSizing: 'border-box',
	},
	stepsContainer: {
		display: 'flex',
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	stepsCount: {
		fontWeight: '500',
		fontStyle: 'normal',
		fontSize: 15,
		lineHeight: 24,
		letterSpacing: 0,
		color: '#fff',
	},
	postsContainer: {
		padding: 20,
	},
	postsTitle: {
		color: '#606773',
		fontSize: 15,
		marginBottom: 10,
		fontWeight: 400,
	},
	post: {
		backgroundColor: '#fff',
		padding: 12,
		boxSizing: 'border-box',
		marginBottom: 10,
		borderRadius: 16,
	},
});
